- hosts: Cluster
  gather_facts: false
  vars:
    iface: test # interface name
    ListenPort: 51000
    nodes:
      TenGZ-2C4G: 10.10.11.1
      TenGZ-2C2G: 10.10.11.2
      AliGZ-2C2G: 10.10.11.3
      AliSZ-2C2G: 10.10.11.4
      AliHK-2C1G: 10.10.11.5
      K3S.lan: 10.10.11.6
  tasks:
    - name: Install
      package:
        name: wireguard-tools
        state: present

    - name: Private
      register: genkey
      command: wg genkey
    - debug:
        msg: "genkey: {{ genkey.stdout }}"

    - name: Public
      register: pubkey
      command:
        cmd: wg pubkey
        stdin: "{{ genkey.stdout }}"
    - debug:
        msg: "pubkey: {{ pubkey.stdout }}"

    - name: Save Public
      copy:
        content: "{{ pubkey.stdout }}"
        dest: /etc/wireguard/{{ iface }}.pub

    - name: Fetch pubkeys
      delegate_to: "{{ item }}"
      loop: "{{ ansible_play_batch }}"
      register: pubkey_list
      command: cat /etc/wireguard/{{ iface }}.pub

    - name: WireGuard config
      template:
        src: server.j2
        dest: /etc/wireguard/{{ iface }}.conf
        owner: root
        group: root
        mode: 0600