- hosts: Cluster
  vars:
    iface: test # interface name
  tasks:
    - name: Install
      package:
        name: wireguard-tools
        state: present

    - name: Private
      register: genkey
      command: wg genkey
    - debug:
        msg: "genkey: {{ genkey.stdout }}"

    - name: Public
      register: pubkey
      command:
        cmd: wg pubkey
        stdin: "{{ genkey.stdout }}"
    - debug:
        msg: "pubkey: {{ pubkey.stdout }}"

    - name: Save Public
      copy:
        content: "{{ pubkey.stdout }}"
        dest: /etc/wireguard/{{ iface }}.pub

    - name: Fetch pubkeys
      delegate_to: "{{ item }}"
      loop: "{{ ansible_play_batch }}"
      register: pubkey_list
      command: cat /etc/wireguard/{{ iface }}.pub

    - name: WireGuard config
      loop: "{{ ansible_play_batch }}"
      loop_control:
        extended: true
      when: item == inventory_hostname
      template:
        src: server.j2
        dest: /etc/wireguard/{{ iface }}.conf
        owner: root
        group: root
        mode: 0600